---
- name: Pull Frontend Docker Image
  docker_image:
    name: "{{ frontend_image }}"
    source: pull

- name: Create Docker Network for Frontend
  docker_network:
    name: "{{ frontend_network }}"
  ignore_errors: yes

- name: Run Frontend Container
  docker_container:
    name: "{{ frontend_container_name }}"
    image: "{{ frontend_image }}"
    networks:
      - name: "{{ frontend_network }}"
    ports:
      - "{{ frontend_host_port }}:{{ frontend_container_port }}"
    state: started
    restart_policy: always
  become: yes
